Card exchanges (test 44-45
vandik-23/devops_project_dtb pull request #20
Opened 2024-12-07 15:36 UTC by Carlomk1

# PR Description
### What is the content of this PR? Which functionality did you add?
- game lets player swap cards with partner at the start of rounds

### Which methods or objects did you modify?
- apply_action
- get_list_action

### Which tests have passed?

Please mark the tests that have passed.

- [ ] Test 1
- [ ] Test 2
- [ ] Test 3
- [ ] Test 4
- [ ] Test 5
- [ ] Test 6
- [ ] Test 7
- [ ] Test 8
- [ ] Test 9
- [ ] Test 10
- [ ] Test 11
- [ ] Test 12
- [ ] Test 13
- [ ] Test 14
- [ ] Test 15
- [ ] Test 16
- [ ] Test 17
- [ ] Test 18
- [ ] Test 19
- [ ] Test 20
- [ ] Test 21
- [ ] Test 22
- [ ] Test 23
- [ ] Test 24
- [ ] Test 25
- [ ] Test 26
- [ ] Test 27
- [ ] Test 28
- [ ] Test 29
- [ ] Test 30
- [ ] Test 31
- [ ] Test 32
- [ ] Test 33
- [ ] Test 34
- [ ] Test 35
- [ ] Test 36
- [ ] Test 37
- [ ] Test 38
- [ ] Test 39
- [ ] Test 40
- [ ] Test 41
- [ ] Test 42
- [ ] Test 43
- [x] Test 44
- [x] Test 45
- [ ] Test 46
- [ ] Test 47
- [ ] Test 48
- [ ] Test 49
- [ ] Test 50
- [ ] Test 51
- [ ] Test 52
- [ ] Test 53
- [ ] Test 54
- [ ] Test 100
- [ ] Test 101
- [ ] Test 102

2024-12-07 18:13 UTC, Carlomk1 commented
Sorry, vergessen alle Tests zu kennzeichnen die erfüllt sind: 1, 3-20, 36-40, 42-46, 51

2024-12-07 21:35 UTC, vandik-23 approved these changes

2024-12-08 10:13 UTC, MrVHub approved these changes

2024-12-09 06:45 UTC, lukasaebi requested changes

2024-12-09 06:45 UTC, lukasaebi commented on server/py/dog.py
> +            return [Action(card=card) for card in unique_cards]
I don't really understand what's going on here? The comment says exchange cards, but the code doesn't exchange cards. What's this for?

2024-12-09 06:45 UTC, lukasaebi commented on server/py/dog.py
> +        # card exchange at the beginning of the round
Two points:
1. Cards should be exchanged each round not only in round 0. According to wiki: "At the beginning of a round, each of the partners exchange one card without revealing it."

2. try to create helper methods. Like this we can keep the public methods like `apply_action` short and clear. I.e. in this case I would do

```python
def _exchange_cards(player: PlayerState) -> list[Action]:
    ... your code
```

and call the method within apply_action like this:

```python
def apply_action(action: Action) -> None:
    ...
    if not self.state.bool_card_exchanged:
        self._exchange_cards(player)
```

2024-12-09 21:16 UTC, Carlomk1 commented
Adapted the code based on Lukas's comments:
`get_list_action`: 
- Here I provide a valid list of actions based on the state of the game, with a helper method `_generate_card_exchange_actions`

`_generate_card_exchange_actions`
- I check for duplicates, so no duplicate actions are following and return a list of valid actions

`apply_action`:
- Checks if card are exchanged, if not i use the helper method `_exchange_cards` for the exchange

`_exchange_cards`:
- perform the exchange

2024-12-11 05:56 UTC, lukasaebi commented on server/py/dog.py
> +        # Checks if card exchange is completed
Such comments are not necessary. You can leave it if you don't want to remove, commit, and push again. But by reading `if not self.state.bool_card_exchanged`, I already know that this code block is executed if card exchange is not executed yet. In general, comments should be more about WHY and not WHAT, since the what should be visible from your code. Of course there can be exceptions some times.

2024-12-12 11:40 UTC, lukasaebi approved these changes

2024-12-12 11:41 UTC, merged