Feature/get player view
vandik-23/devops_project_dtb pull request #6
Opened 2024-11-25 22:52 UTC by vandik-23

- added get_player_view function
 - changed print_state with adding masked_state

2024-11-26 07:49 UTC, lukasaebi requested changes

2024-11-26 07:49 UTC, lukasaebi commented on server/py/hangman.py
> +        masked_state = self.get_player_view()
Diese Methode musst du nicht bearbeiten, da Viktor diese bereits bearbeitet hat. Wenn du diese jetzt auch bearbeitest wird es zu merge conflicts kommen, besonders, da dein Code der `print_state` Method anders ist als jener von Viktor.

Wenn du willst, dass alle Änderungen, die in der Zwischenzeit gemacht wurden und in main gemerged wurden (sprich alle bisherigen PRs), in deinem get_player_view branch ersichtlich sind, musst du in deinem branch lokal `git pull origin main` ausführen. Das zieht alle Änderungen vom remote main branch zu dir lokal in deinen get_player_view branch.

Step-by-step:
1. `git branch` - Checke, ob du im get_player_view branch bist
2. `git checkout feature/get_player_view` Falls du NICHT im get_player_view branch bist 
3. `git pull origin main` - updated deinen lokalen branch auf den Stand des remote main branch
4. `git push origin feature/get_player_view` - updated deinen remote branch + deinen PR

2024-11-26 07:49 UTC, lukasaebi commented on server/py/hangman.py
>      def get_player_view(self, idx_player: int) -> HangmanGameState:
In der `get_player_view` Methode gibt es den Parameter `idx_player`. Ich denke, dieser ist falsch für den Hangman use-case, da es ein Einspieler-Spiel ist. Damit man diesen Parameter aber nicht immer passen muss, wenn man die Method `get_player_view` aufruft, würde ich diese Zeile forlgendermassen ändern:

```suggestion
    def get_player_view(self, idx_player: Optional[int] = None) -> HangmanGameState:
```

2024-11-27 16:00 UTC, vandik-23 commented on server/py/hangman.py
> +        masked_state = self.get_player_view()
"revert changes print_state function as advised by review"

2024-11-27 16:00 UTC, merged